function COM = COM_all(in1,in2)
%COM_ALL
%    COM = COM_ALL(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 5.8.
%    03-Oct-2013 23:05:50

c1 = in2(2,:);
c2 = in2(3,:);
dth = in1(4,:);
dy = in1(2,:);
l = in2(1,:);
m1 = in2(4,:);
m2 = in2(5,:);
mh = in2(6,:);
th = in1(3,:);
y = in1(1,:);
t2 = cos(th);
t3 = sin(th);
t4 = m1+m2+mh;
t5 = 1.0./t4;
t6 = c2.*t3;
t7 = l.*t3;
t8 = c2.*t2;
COM = [-t5.*(m2.*(t8-l.*t2)-c1.*m1.*t2);t5.*(m2.*(t6+t7+y)+m1.*(y+c1.*t3)+mh.*(y+l.*t3.*2.0));dth.*t5.*(m2.*(t6-t7)-c1.*m1.*t3);dy+dth.*t5.*(m2.*(t8+l.*t2)+c1.*m1.*t2+l.*mh.*t2.*2.0)];
