function R = z2R_all(in1,in2)
%Z2R_ALL
%    R = Z2R_ALL(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 5.8.
%    03-Oct-2013 23:05:50

l = in2(1,:);
th = in1(3,:);
y = in1(1,:);
t2 = sin(th);
R = [y*0.0;y;l.*cos(th);y+l.*t2;y*0.0;y+l.*t2.*2.0];
