function bi = bi_all(in1,in2)
%BI_ALL
%    BI = BI_ALL(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 5.8.
%    03-Oct-2013 23:05:50

I1 = in2(7,:);
I2 = in2(8,:);
c1 = in2(2,:);
c2 = in2(3,:);
dth = in1(4,:);
dy = in1(2,:);
l = in2(1,:);
m1 = in2(4,:);
m2 = in2(5,:);
mh = in2(6,:);
th = in1(3,:);
t2 = cos(th);
t3 = sin(th);
t4 = c2.*t3-l.*t3;
t5 = c2.*t2+l.*t2;
t6 = c1.^2;
t7 = t2.^2;
t8 = c2.*t2.*2.0;
t9 = l.*t2.*2.0;
t10 = t8+t9;
t11 = m2.*t10.*(1.0./2.0);
t12 = c1.*m1.*t2;
t13 = l.*mh.*t2.*2.0;
t14 = t11+t12+t13;
bi = [dth.*t14+dy.*(m1+m2+mh);dy.*t14+dth.*(I1+I2+m1.*(t6.*t7.*2.0+t3.^2.*t6.*2.0).*(1.0./2.0)+m2.*(t4.^2.*2.0+t5.^2.*2.0).*(1.0./2.0)+l.^2.*mh.*t7.*4.0);0.0];
